### ISSUE TITLE
SMTP Error

### ISSUE THREAD

**Issue by jon-bit** [mailvelope/keyserver#120]
I'm geting the error 

`  1) Email Integration Tests
       _sendHelper
         should work:
     Error: Sending email to user failed
      at Object.exports.throw (src/service/util.js:100:15)
      at Email._sendHelper (src/email/email.js:118:17)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (test/integration/email-test.js:49:20)

  2) Email Integration Tests
       send verifyKey template
         should send plaintext email:
     Error: Sending email to user failed
      at Object.exports.throw (src/service/util.js:100:15)
      at Email._sendHelper (src/email/email.js:118:17)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (test/integration/email-test.js:57:7)

  3) Email Integration Tests
       send verifyKey template
         should send pgp encrypted email:
     Error: Sending email to user failed
      at Object.exports.throw (src/service/util.js:100:15)
      at Email._sendHelper (src/email/email.js:118:17)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (test/integration/email-test.js:61:7)

  4) Email Integration Tests
       send verifyRemove template
         should send plaintext email:
     Error: Sending email to user failed
      at Object.exports.throw (src/service/util.js:100:15)
      at Email._sendHelper (src/email/email.js:118:17)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (test/integration/email-test.js:68:7)

  5) Email Integration Tests
       send verifyRemove template
         should send pgp encrypted email:
     Error: Sending email to user failed
      at Object.exports.throw (src/service/util.js:100:15)
      at Email._sendHelper (src/email/email.js:118:17)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (test/integration/email-test.js:72:7)
`

when I run _npm test_ and I don't know why. If my mail server is running mail cow dockerized and this is my config 

`'use strict';

module.exports = {

  log: {
    level: process.env.LOG_LEVEL = 'silly'
  },

  papertrail: {
    host: process.env.PAPERTRAIL_HOST,
    port: process.env.PAPERTRAIL_PORT
  },

  server: {
    port: process.env.PORT = 8888,
    httpsUpgrade: process.env.HTTPS_UPGRADE = true,
    httpsKeyPin: process.env.HTTPS_KEY_PIN,
    httpsKeyPinBackup: process.env.HTTPS_KEY_PIN_BACKUP
  },

  mongo: {
    uri: process.env.MONGO_URI = '127.0.0.1:27017/keyserver-test',
    user: process.env.MONGO_USER = 'mydbusermane',
    pass: process.env.MONGO_PASS = 'mydbpassword'
  },

  email: {
    host: process.env.SMTP_HOST = 'mail.mydomain.com',
    port: process.env.SMTP_PORT = 587,
    tls: process.env.SMTP_TLS = false,
    starttls: process.env.SMTP_STARTTLS = true,
    pgp: process.env.SMTP_PGP = false,
    auth: {
      user: process.env.SMTP_USER = 'pgp@mydomain.com',
      pass: process.env.SMTP_PASS = 'mypassword'
    },
    sender: {
      name: process.env.SENDER_NAME = 'my name',
      email: process.env.SENDER_EMAIL = 'pgp@mycomain.com'
    }
  },

  publicKey: {
    purgeTimeInDays: process.env.PUBLIC_KEY_PURGE_TIME = 30
  }

};
`
What am I doing wrong because everything else seems fine and passes without problem.
Thanks to everyone who helps! :)

**Comment by toberndo** [comment]
The key server just hands over the SMPT parameters to nodemailer, therefore nodemailer might be a better place to search for help regarding compatibility with your email provider.
