### ISSUE TITLE
Ubuntu 14.04 Install Issues

### ISSUE THREAD

**Issue by jaschadub** [mailvelope/keyserver#18]
When running `npm test`:

```> mailvelope-keyserver@1.2.6 test /home/ubuntu/keyserver
> : ${NODE_ENV=development} && grunt test

Running "jshint:all" (jshint) task
>> 18 files lint free.

Running "jscs:src" (jscs) task
>> 18 files without code style errors.

Running "mochaTest:test" (mochaTest) task

/home/ubuntu/keyserver/test/unit/email-test.js:5
const expect = require('chai').expect;
^^^^^
>> Mocha exploded!
>> SyntaxError: Use of const in strict mode.
>>     at Module._compile (module.js:439:25)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (/home/ubuntu/keyserver/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at /home/ubuntu/keyserver/node_modules/mocha/lib/mocha.js:222:27
>>     at Array.forEach (native)
>>     at Mocha.loadFiles (/home/ubuntu/keyserver/node_modules/mocha/lib/mocha.js:219:14)
>>     at Mocha.run (/home/ubuntu/keyserver/node_modules/mocha/lib/mocha.js:487:10)
>>     at MochaWrapper.run (/home/ubuntu/keyserver/node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:44:13)
>>     at /home/ubuntu/keyserver/node_modules/grunt-mocha-test/tasks/mocha-test.js:84:20
>>     at capture (/home/ubuntu/keyserver/node_modules/grunt-mocha-test/tasks/mocha-test.js:31:5)
>>     at Object.<anonymous> (/home/ubuntu/keyserver/node_modules/grunt-mocha-test/tasks/mocha-test.js:79:5)
>>     at Object.<anonymous> (/home/ubuntu/keyserver/node_modules/grunt/lib/grunt/task.js:255:15)
>>     at Object.thisTask.fn (/home/ubuntu/keyserver/node_modules/grunt/lib/grunt/task.js:73:16)
>>     at Object.<anonymous> (/home/ubuntu/keyserver/node_modules/grunt/lib/util/task.js:294:30)
>>     at Task.runTaskFn (/home/ubuntu/keyserver/node_modules/grunt/lib/util/task.js:244:24)
>>     at Task.<anonymous> (/home/ubuntu/keyserver/node_modules/grunt/lib/util/task.js:293:12)
>>     at /home/ubuntu/keyserver/node_modules/grunt/lib/util/task.js:220:11
>>     at process._tickDomainCallback (node.js:459:13)
Warning: Task "mochaTest:test" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! weird error 3
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

On current HEAD and trying with last release get same result.

**Comment by jaschadub** [comment]
Upgrading to latest node fixes issue.
